[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "signplus_developer_api_v2_spec_sdk"
version = "1.0.0"
description = """Integrate legally-binding electronic signature to your workflow"""
readme = "PyPI_README.md"
requires-python = ">=3.9"
dependencies = [
    "requests>=2.31.0",
    "pydantic>=2.0.0,<3.0.0"
]
