from .create_envelope_request import CreateEnvelopeRequest
from .envelope import Envelope
from .create_envelope_from_template_request import CreateEnvelopeFromTemplateRequest
from .list_envelopes_request import ListEnvelopesRequest
from .list_envelopes_response import ListEnvelopesResponse
from .document import Document
from .list_envelope_documents_response import ListEnvelopeDocumentsResponse
from .add_envelope_document_request import AddEnvelopeDocumentRequest
from .set_envelope_dynamic_fields_request import SetEnvelopeDynamicFieldsRequest
from .add_envelope_signing_steps_request import AddEnvelopeSigningStepsRequest
from .set_envelope_attachments_settings_request import (
    SetEnvelopeAttachmentsSettingsRequest,
)
from .envelope_attachments import EnvelopeAttachments
from .set_envelope_attachments_placeholders_request import (
    SetEnvelopeAttachmentsPlaceholdersRequest,
)
from .rename_envelope_request import RenameEnvelopeRequest
from .set_envelope_comment_request import SetEnvelopeCommentRequest
from .envelope_notification import EnvelopeNotification
from .set_envelope_expiration_request import SetEnvelopeExpirationRequest
from .set_envelope_legality_level_request import SetEnvelopeLegalityLevelRequest
from .annotation import Annotation
from .list_envelope_document_annotations_response import (
    ListEnvelopeDocumentAnnotationsResponse,
)
from .add_annotation_request import AddAnnotationRequest
from .create_template_request import CreateTemplateRequest
from .template import Template
from .list_templates_request import ListTemplatesRequest
from .list_templates_response import ListTemplatesResponse
from .add_template_document_request import AddTemplateDocumentRequest
from .list_template_documents_response import ListTemplateDocumentsResponse
from .add_template_signing_steps_request import AddTemplateSigningStepsRequest
from .rename_template_request import RenameTemplateRequest
from .set_template_comment_request import SetTemplateCommentRequest
from .list_template_annotations_response import ListTemplateAnnotationsResponse
from .list_template_document_annotations_response import (
    ListTemplateDocumentAnnotationsResponse,
)
from .create_webhook_request import CreateWebhookRequest
from .webhook import Webhook
from .list_webhooks_request import ListWebhooksRequest
from .list_webhooks_response import ListWebhooksResponse
from .envelope_legality_level import EnvelopeLegalityLevel
from .envelope_flow_type import EnvelopeFlowType
from .envelope_status import EnvelopeStatus
from .signing_step import SigningStep
from .recipient import Recipient
from .recipient_role import RecipientRole
from .recipient_verification import RecipientVerification
from .recipient_verification_type import RecipientVerificationType
from .page import Page
from .attachment_settings import AttachmentSettings
from .attachment_placeholders_per_recipient import AttachmentPlaceholdersPerRecipient
from .attachment_placeholder import AttachmentPlaceholder
from .attachment_placeholder_file import AttachmentPlaceholderFile
from .envelope_order_field import EnvelopeOrderField
from .dynamic_field import DynamicField
from .attachment_placeholder_request import AttachmentPlaceholderRequest
from .annotation_type import AnnotationType
from .annotation_signature import AnnotationSignature
from .annotation_initials import AnnotationInitials
from .annotation_text import AnnotationText
from .annotation_date_time import AnnotationDateTime
from .annotation_checkbox import AnnotationCheckbox
from .annotation_font import AnnotationFont
from .annotation_font_family import AnnotationFontFamily
from .annotation_date_time_format import AnnotationDateTimeFormat
from .annotation_checkbox_style import AnnotationCheckboxStyle
from .template_signing_step import TemplateSigningStep
from .template_recipient import TemplateRecipient
from .template_recipient_role import TemplateRecipientRole
from .template_order_field import TemplateOrderField
from .webhook_event import WebhookEvent

# Rebuild models to resolve circular forward references
# This ensures Pydantic can properly validate models that reference each other
CreateEnvelopeRequest.model_rebuild()
Envelope.model_rebuild()
CreateEnvelopeFromTemplateRequest.model_rebuild()
ListEnvelopesRequest.model_rebuild()
ListEnvelopesResponse.model_rebuild()
Document.model_rebuild()
ListEnvelopeDocumentsResponse.model_rebuild()
AddEnvelopeDocumentRequest.model_rebuild()
SetEnvelopeDynamicFieldsRequest.model_rebuild()
AddEnvelopeSigningStepsRequest.model_rebuild()
SetEnvelopeAttachmentsSettingsRequest.model_rebuild()
EnvelopeAttachments.model_rebuild()
SetEnvelopeAttachmentsPlaceholdersRequest.model_rebuild()
RenameEnvelopeRequest.model_rebuild()
SetEnvelopeCommentRequest.model_rebuild()
EnvelopeNotification.model_rebuild()
SetEnvelopeExpirationRequest.model_rebuild()
SetEnvelopeLegalityLevelRequest.model_rebuild()
Annotation.model_rebuild()
ListEnvelopeDocumentAnnotationsResponse.model_rebuild()
AddAnnotationRequest.model_rebuild()
CreateTemplateRequest.model_rebuild()
Template.model_rebuild()
ListTemplatesRequest.model_rebuild()
ListTemplatesResponse.model_rebuild()
AddTemplateDocumentRequest.model_rebuild()
ListTemplateDocumentsResponse.model_rebuild()
AddTemplateSigningStepsRequest.model_rebuild()
RenameTemplateRequest.model_rebuild()
SetTemplateCommentRequest.model_rebuild()
ListTemplateAnnotationsResponse.model_rebuild()
ListTemplateDocumentAnnotationsResponse.model_rebuild()
CreateWebhookRequest.model_rebuild()
Webhook.model_rebuild()
ListWebhooksRequest.model_rebuild()
ListWebhooksResponse.model_rebuild()
SigningStep.model_rebuild()
Recipient.model_rebuild()
RecipientVerification.model_rebuild()
Page.model_rebuild()
AttachmentSettings.model_rebuild()
AttachmentPlaceholdersPerRecipient.model_rebuild()
AttachmentPlaceholder.model_rebuild()
AttachmentPlaceholderFile.model_rebuild()
DynamicField.model_rebuild()
AttachmentPlaceholderRequest.model_rebuild()
AnnotationSignature.model_rebuild()
AnnotationInitials.model_rebuild()
AnnotationText.model_rebuild()
AnnotationDateTime.model_rebuild()
AnnotationCheckbox.model_rebuild()
AnnotationFont.model_rebuild()
TemplateSigningStep.model_rebuild()
TemplateRecipient.model_rebuild()
